# Generated by Django 5.2.1 on 2025-05-26 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_remove_category_id_category_cat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='44d2a920-4f5f-4002-b6cc-f7ba721db9f4', on_delete=django.db.models.deletion.CASCADE, to='apis.category'),
        ),
    ]
