# Generated by Django 5.2.1 on 2025-05-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(related_name='carts', through='apis.CartItem', to='apis.product'),
        ),
    ]
