# Generated by Django 5.2.1 on 2025-05-27 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_cart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
